### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by rborgesm** [KiddLab/random-sample-by-ppm#1]
This code is working most times but occasionally the simulations fail with the following error (which is a problem when running many simulations because the job then fails):

```
# example 1

Traceback (most recent call last):
  File "sample-based-on-ppm.py", line 74, in <module>
    randSel = sampleutils.select_random_position_with_weights(myData)
  File "$PATH/random-sample-by-ppm/sampleutils.py", line 186, in select_random_position_with_weights
    score_selected(data,randSel)
  File "$PATH/random-sample-by-ppm/sampleutils.py", line 232, in score_selected
    seqScore = score_seq_ppm(extractedSeq,data['ppmMat'])
  File "$PATH/random-sample-by-ppm/sampleutils.py", line 177, in score_seq_ppm
    score = score * myPPM[c,i]
KeyError: ('R', 4)


# example 2
Traceback (most recent call last):
  File "sample-based-on-ppm.py", line 74, in <module>
    randSel = sampleutils.select_random_position_with_weights(myData)
  File "$PATH/random-sample-by-ppm/sampleutils.py", line 186, in select_random_position_with_weights
    score_selected(data,randSel)
  File "$PATH/random-sample-by-ppm/sampleutils.py", line 232, in score_selected
    seqScore = score_seq_ppm(extractedSeq,data['ppmMat'])
  File "$PATH/random-sample-by-ppm/sampleutils.py", line 177, in score_seq_ppm
    score = score * myPPM[c,i]
KeyError: ('R', 4)

# example 3

Traceback (most recent call last):
  File "sample-based-on-ppm.py", line 74, in <module>
    randSel = sampleutils.select_random_position_with_weights(myData)
  File "$PATH/random-sample-by-ppm/sampleutils.py", line 186, in select_random_position_with_weights
    score_selected(data,randSel)
  File "$PATH/random-sample-by-ppm/sampleutils.py", line 214, in score_selected
    seqScore = score_seq_ppm(extractedSeq,data['ppmMat'])
  File "$PATH/random-sample-by-ppm/sampleutils.py", line 177, in score_seq_ppm
    score = score * myPPM[c,i]
KeyError: ('W', 2)

# example 4
Traceback (most recent call last):
  File "sample-based-on-ppm.py", line 74, in <module>
    randSel = sampleutils.select_random_position_with_weights(myData)
  File "$PATH/random-sample-by-ppm/sampleutils.py", line 186, in select_random_position_with_weights
    score_selected(data,randSel)
  File "$PATH/random-sample-by-ppm/sampleutils.py", line 214, in score_selected
    seqScore = score_seq_ppm(extractedSeq,data['ppmMat'])
  File "$PATH/random-sample-by-ppm/sampleutils.py", line 177, in score_seq_ppm
    score = score * myPPM[c,i]
KeyError: ('W', 4)
```

Do you know what could be causing this? I'm using hg38.

**Comment by jmkidd** [comment]
Hi.  It looks like the error is because your fasta has non ACGTN characters in it (W and R are ambiguity codes).  Could you share or check the files you are using?

**Comment by rborgesm** [comment]
That's correct, I'm using the reference hg38 sequence and it does contain ambiguous codes:

E.g.
`CTTTCTAGTTTTTACCTWAAGAAATTCCTTTATCACCATAGGCTTCAAAGTGCTCTAAAA`

After converting these to N's the code worked without any issues, thank you for the quick reply!
